[profile.default]
src = "src"
out = "out"
solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = false
allow_paths = ["../../lib"]
remappings = ["safe/=../../lib/safe-v1.4.1/contracts/"]